[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="MenuUtils" type="com.slyak.web.util.MenuUtils" --]
[#import '/com/slyak/web/support/freemarker/slyak.ftl' as slyak]
[#import '/com/slyak/web/support/freemarker/slyak-ui.ftl' as slyakUI]